name: gun_range_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  # cloudflare_turnstile: ^3.6.2
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^9.2.0
  go_router: ^15.1.2
  google_fonts: ^6.3.0
  http: ^1.6.0
  pdf: ^3.11.3
  pdfrx: ^1.0.101
  share_plus: ^12.0.1
  skeletonizer: ^1.4.3
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/maps/
    - assets/logo/
    - assets/fonts/Roboto-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo_bigger.svg"
